export const url = {
    URL_LOGIN: "/login",
    URL_REGISTER: '/register',
    URL_PROMPTEMAIL: '/email',
    URL_PROMPTNAME: '/username',
    URL_USERMSG: '/user',
    URL_MODIFYUSER: '/modifyUser',
    URL_FOLLOWLIST: '/user/followList',
    URL_FANSLIST: '/user/fansList',
    URL_VIDEO: "/video",
    URL_ALLVIDEOTYPE: '/video/allVideoType',
    URL_VIDEOTYPE: "/videoType/1&&4",
    URL_USERHOME: '/user/userhome',
    URL_COLLECTIONS: '/user/collections',
    URL_UPLOADVIDEO:'/user/video',
    URL_PUT_PLAYERCOUNT:'/video/playcount/',
    URL_PUT_PRAISEVIDEO:'/video/top/',
    URL_PUT_TRAMPLEVIDEO:'/video/trample/',
    URL_PUT_FOLLOW:'/user/follow/',
}